

# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  server:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.server
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydb

  client:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.client
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - server
